### ISSUE TITLE
Don't base64-encode conditions and fulfillments

### ISSUE THREAD

**Issue by michielbdejong** [interledgerjs/btp-packet#8]
Just like liquidity curves are left as buffers in https://github.com/interledgerjs/ilp-packet#ilqpliquidityresponse, we should leave conditions and fulfillments as buffers too.

We also already pass ILP payments, and other protocol data as buffers.

This goes for both the values returned by deserialize functions and the values expected by serialize functions, although for the latter, just like for the rejectionReason, we can overload, so if you give it a string instead of a buffer, it should still interpret it as base64.

**Comment by adrianhopebailie** [comment]
No longer relevant
